import { otherModeOfPayment } from "../constants/Constants";

export interface PaymentState {
  totalPurchase: string;
  totalPurchaseIsInValid: boolean;
  totalPurchaseIsValid: boolean;
  totalPurchaseValidationMessage: string;
  pendingAmount: string;
  dynamicPendingAmount: string;
  pendingAmountIsInValid: boolean;
  pendingAmountIsValid: boolean;
  pendingAmountValidationMessage: string;
  otherModeOptions: any[];
  otherModeOfPayment: boolean;
  amount: string;
  amountIsInValid: boolean;
  amountIsValid: boolean;
  totalPurchaseAmountIsDisabled: boolean;
  amountValidationMessage: string;
  paymentDescription: string;
  paymentDescriptionIsInValid: boolean;
  paymentDescriptionIsValid: boolean;
  paymentDescriptionValidationMessage: string;
  enableSecondary: boolean;
  enablePrimary: boolean;
  isSecondaryButtonDisabled: boolean;
  partiallyPaid: boolean;
  primary: {
    cardHolderName: string;
    cardNumber: string;
    cardType: string;
    expDate: string;
    cvv: string;
    amount: string;
    cardHolderNameIsInValid: boolean;
    cardHolderNameIsValid: boolean;
    cardHolderValidationMessage: string;
    cardNumberIsInValid: boolean;
    cardNumberIsValid: boolean;
    cardNumberValidationMessage: string;
    cardTypeIsInValid: boolean;
    cardTypeIsValid: boolean;
    cardTypeValidationMessage: string;
    expDateIsInValid: boolean;
    expDateIsValid: boolean;
    expDateValidationMessage: string;
    cvvIsInValid: boolean;
    cvvIsValid: boolean;
    cvvValidationMessage: string;
    amountIsInValid: boolean;
    amountIsValid: boolean;
    amountValidationMessage: string;
  };
  secondary: {
    cardHolderName: string;
    cardNumber: string;
    cardType: string;
    expDate: string;
    cvv: string;
    amount: string;
    cardHolderNameIsInValid: boolean;
    cardHolderNameIsValid: boolean;
    cardHolderValidationMessage: string;
    cardNumberIsInValid: boolean;
    cardNumberIsValid: boolean;
    cardNumberValidationMessage: string;
    cardTypeIsInValid: boolean;
    cardTypeIsValid: boolean;
    cardTypeValidationMessage: string;
    expDateIsInValid: boolean;
    expDateIsValid: boolean;
    expDateValidationMessage: string;
    cvvIsInValid: boolean;
    cvvIsValid: boolean;
    cvvValidationMessage: string;
    amountIsInValid: boolean;
    amountIsValid: boolean;
    amountValidationMessage: string;
  };
  cardTypeOptions: any;
}

export const defaultPaymentState: PaymentState = {
  totalPurchase: "",
  totalPurchaseIsInValid: false,
  totalPurchaseIsValid: false,
  totalPurchaseValidationMessage: "",
  pendingAmount: "",
  dynamicPendingAmount: "",
  pendingAmountIsInValid: false,
  pendingAmountIsValid: false,
  pendingAmountValidationMessage: "",
  otherModeOptions: otherModeOfPayment,
  otherModeOfPayment: false,
  amount: "",
  totalPurchaseAmountIsDisabled: false,
  amountIsInValid: false,
  amountIsValid: false,
  amountValidationMessage: "",
  paymentDescription: "",
  paymentDescriptionIsInValid: false,
  paymentDescriptionIsValid: false,
  paymentDescriptionValidationMessage: "",
  enableSecondary: false,
  enablePrimary: true,
  isSecondaryButtonDisabled: false,
  partiallyPaid: false,
  primary: {
    cardNumber: "",
    cardType: "",
    expDate: "",
    cvv: "",
    amount: "",
    cardHolderName: "",
    cardHolderNameIsInValid: false,
    cardHolderNameIsValid: false,
    cardHolderValidationMessage: "",
    cardNumberIsInValid: false,
    cardNumberIsValid: false,
    cardNumberValidationMessage: "",
    cardTypeIsInValid: false,
    cardTypeIsValid: false,
    cardTypeValidationMessage: "",
    expDateIsInValid: false,
    expDateIsValid: false,
    expDateValidationMessage: "",
    cvvIsInValid: false,
    cvvIsValid: false,
    cvvValidationMessage: "",
    amountIsInValid: false,
    amountIsValid: false,
    amountValidationMessage: "",
  },
  secondary: {
    cardNumber: "",
    cardType: "",
    expDate: "",
    cvv: "",
    amount: "",
    cardHolderName: "",
    cardHolderNameIsInValid: false,
    cardHolderNameIsValid: false,
    cardHolderValidationMessage: "",
    cardNumberIsInValid: false,
    cardNumberIsValid: false,
    cardNumberValidationMessage: "",
    cardTypeIsInValid: false,
    cardTypeIsValid: false,
    cardTypeValidationMessage: "",
    expDateIsInValid: false,
    expDateIsValid: false,
    expDateValidationMessage: "",
    cvvIsInValid: false,
    cvvIsValid: false,
    cvvValidationMessage: "",
    amountIsInValid: false,
    amountIsValid: false,
    amountValidationMessage: "",
  },
  cardTypeOptions: [],
};

export const defaultSecondaryCardState: PaymentState["secondary"] = {
  cardNumber: "",
  cardType: "",
  expDate: "",
  cvv: "",
  amount: "",
  cardHolderName: "",
  cardHolderNameIsInValid: false,
  cardHolderNameIsValid: false,
  cardHolderValidationMessage: "",
  cardNumberIsInValid: false,
  cardNumberIsValid: false,
  cardNumberValidationMessage: "",
  cardTypeIsInValid: false,
  cardTypeIsValid: false,
  cardTypeValidationMessage: "",
  expDateIsInValid: false,
  expDateIsValid: false,
  expDateValidationMessage: "",
  cvvIsInValid: false,
  cvvIsValid: false,
  cvvValidationMessage: "",
  amountIsInValid: false,
  amountIsValid: false,
  amountValidationMessage: "",
};
